Feature/pcrr 143 invest
paycer-protocol/paycer-prototype pull request #130
Opened 2022-02-13 23:51 UTC by stompudown

2022-02-14 02:37 UTC, ketsuo requested changes

2022-02-14 02:37 UTC, ketsuo commented on src/components/organisms/invest/helper/set-field-values.tsx
> +const setFieldValues = (setFieldValue, values, depositAmount) => {
Please rename the method. e.g calculateFieldValues

2022-02-14 02:37 UTC, ketsuo commented on src/config/network.ts
> +    ChainId.Kovan
Please remove kovan. We dont use in this stage.

2022-02-14 02:37 UTC, ketsuo commented on src/config/network.ts
> +  ChainId.Kovan
Please remove kovan. We dont use in this stage.

2022-02-14 02:37 UTC, ketsuo commented on src/config/network.ts
> +  ChainId.Kovan
Please remove kovan. We dont use in this stage.

2022-02-14 02:37 UTC, ketsuo commented on src/providers/strategies.ts
> +      [ChainId.Kovan]: '0xAaD7328bCC81AC7D8ae9187d7F10B503E3d38Eb8'
Please remove kovan. We dont use in this stage and all from below code.

2022-02-17 10:33 UTC, stompudown commented on src/components/organisms/invest/helper/set-field-values.tsx
> +const setFieldValues = (setFieldValue, values, depositAmount) => {
Done

2022-02-17 10:33 UTC, stompudown commented on src/providers/strategies.ts
> +      [ChainId.Kovan]: '0xAaD7328bCC81AC7D8ae9187d7F10B503E3d38Eb8'
Done

2022-02-17 10:33 UTC, stompudown commented on src/config/network.ts
> +  ChainId.Kovan
Done

2022-02-17 10:33 UTC, stompudown commented on src/config/network.ts
> +  ChainId.Kovan
Done

2022-02-17 10:33 UTC, stompudown commented on src/config/network.ts
> +    ChainId.Kovan
Done

2022-02-19 11:49 UTC, ketsuo approved these changes

2022-02-21 04:53 UTC, merged